---
- name: Install Automation Controller
  hosts: localhost
  become: true
  vars_files:
    - inventory_vars/variables.yml
    - vars/installer_vars.yml
  roles:
    - redhat_cop.aap_utilities.aap_setup_download
    - redhat_cop.aap_utilities.aap_setup_prepare
    - redhat_cop.aap_utilities.aap_setup_install
